<?php
require_once __DIR__ . '/vendor/autoload.php';

class ModernInvoice extends \TCPDF {
    // Custom Header
    public function Header() {
        // Logo (replace with your actual logo path)
        $logoPath = 'logo.png';
        if (file_exists($logoPath)) {
            $this->Image($logoPath, 15, 10, 40, '', 'PNG', '', 'T', false, 300, '', false, false, 0);
        }

        // Company Details
        $this->SetFont('helvetica', 'B', 12);
        $this->SetTextColor(50, 50, 50);
        $this->Cell(0, 15, 'Katagasma Hanwella', 0, 1, 'R');
        
        $this->SetFont('helvetica', '', 10);
        $this->Cell(0, 6, 'Contact: 0771168439', 0, 1, 'R');
        $this->Cell(0, 6, 'Email: info@katagasmahanwella.com', 0, 1, 'R');
    }

    // Custom Footer
    public function Footer() {
        $this->SetY(-20);
        $this->SetFont('helvetica', 'I', 8);
        $this->SetTextColor(100, 100, 100);
        $this->Cell(0, 10, 'Invoice generated by Chox Trading', 0, 0, 'C');
        $this->Cell(0, 10, 'Page ' . $this->getAliasNumPage() . ' of ' . $this->getAliasNbPages(), 0, 0, 'R');
    }
}

if (isset($_GET['billNo']) && isset($_GET['data'])) {
    // Set the time zone to Asia/Colombo
    date_default_timezone_set('Asia/Colombo');

    // Retrieve data from URL parameters
    $billNo = $_GET['billNo'];
    $invoiceData = json_decode(urldecode($_GET['data']), true);
    $totalAmount = $_GET['totalAmount'];
    $cash = $_GET['cash'];
    $balance = $_GET['balance'];

    // Create a new custom TCPDF instance
    $pdf = new ModernInvoice('P', 'mm', 'A4', true, 'UTF-8', false);

    // Set document properties
    $pdf->SetCreator(PDF_CREATOR);
    $pdf->SetTitle("Invoice #$billNo");
    $pdf->SetSubject("Sales Invoice");
    
    // Remove default header/footer
    $pdf->setPrintHeader(true);
    $pdf->setPrintFooter(true);

    // Set margins
    $pdf->SetMargins(15, 40, 15);
    $pdf->SetHeaderMargin(10);
    $pdf->SetFooterMargin(15);

    // Add a page
    $pdf->AddPage();

    // Invoice Details Section
    $pdf->SetFont('helvetica', 'B', 14);
    $pdf->SetTextColor(0, 0, 0);
    $pdf->Cell(0, 10, 'TAX INVOICE', 0, 1, 'C');

    $pdf->SetFont('helvetica', '', 10);
    $pdf->Cell(0, 6, 'Invoice Number: ' . $billNo, 0, 1, 'L');
    $pdf->Cell(0, 6, 'Date: ' . date('Y-m-d H:i:s'), 0, 1, 'L');
    $pdf->Ln(5);

    // Table Headers
    $pdf->SetFont('helvetica', 'B', 10);
    $pdf->SetFillColor(230, 230, 230);
    $pdf->Cell(100, 10, 'Product Description', 1, 0, 'C', 1);
    $pdf->Cell(30, 10, 'Quantity', 1, 0, 'C', 1);
    $pdf->Cell(30, 10, 'Unit Price', 1, 0, 'C', 1);
    $pdf->Cell(30, 10, 'Total', 1, 1, 'C', 1);

    // Table Contents
    $pdf->SetFont('helvetica', '', 10);
    foreach ($invoiceData as $item) {
        $pdf->Cell(100, 10, $item['name'], 1, 0, 'L');
        $pdf->Cell(30, 10, isset($item['quantity']) ? $item['quantity'] : '1', 1, 0, 'C');
        $pdf->Cell(30, 10, 'Rs: ' . number_format($item['price'], 2), 1, 0, 'R');
        
        $itemTotal = isset($item['quantity']) ? $item['price'] * $item['quantity'] : $item['price'];
        $pdf->Cell(30, 10, 'Rs: ' . number_format($itemTotal, 2), 1, 1, 'R');
    }

    // Summary Section
    $pdf->Ln(10);
    $pdf->SetFont('helvetica', 'B', 12);
    
    $summaryX = $pdf->GetX();
    $summaryY = $pdf->GetY();

    $pdf->Cell(120, 10, 'Total Amount', 1, 0, 'L');
    $pdf->Cell(30, 10, 'Rs: ' . number_format($totalAmount, 2), 1, 1, 'R');

    $pdf->Cell(120, 10, 'Cash Paid', 1, 0, 'L');
    $pdf->Cell(30, 10, 'Rs: ' . number_format($cash, 2), 1, 1, 'R');

    $pdf->Cell(120, 10, 'Balance', 1, 0, 'L');
    $pdf->Cell(30, 10, 'Rs: ' . number_format($balance, 2), 1, 1, 'R');

    // Output the PDF
    $pdf->Output('invoice_' . $billNo . '.pdf', 'I');

    // After the PDF is displayed, redirect to a page with JavaScript to show the alert
    echo '<script>
        window.onload = function() {
            alert("Invoice generated successfully!");
            window.location.href = "dashboard.php"; // Redirect to dashboard or any other page
        };
    </script>';
} else {
    echo "Invalid invoice data.";
}
?>